jobs:
 # - name: generate-mongo-image-manifest-3
#    type: manifest
 #   steps:
 #     - GET: mongo-image
  #    - GET: myEcsParams

  - name: generate-mongo-image-manifest-6
    type: manifest
    steps:
      - GET: mongo-image
#      - GET: deploy-service

 # - name: deploy-service
#    type: ecsDeploy
#    steps:
#      - GET: generate-mongo-image-manifest-3
#      - GET: myEcsCluster

  - name: deploy-service-7
    type: dclDeploy
    steps:
      - GET: generate-mongo-image-manifest-6
      - GET: myDclCluster
      - GET: myEcsParams
 #     - GET: myOtherEcsParams
