# Language setting
language: python

# Version number
python:
  - 2.7

build:
  ci:
    - python --version

resources:
  - name: bitbucket-integration-shippable-yml
    type: integration
    integration: bitbucket
    flags: integration

jobs:
  - name: runSh-shippable-yml
    type: runSh
    flags: integration
    TASK:
      - script: "echo true"
