jobs:
 # - name: generate-mongo-image-manifest-3
#    type: manifest
 #   steps:
 #     - GET: mongo-image
  #    - GET: myEcsParams

  - name: foo
    type: release
    options:
      action: test
    steps:
      - IN: triggerTwo
      - IN: version-resource-1
     # - GET: myEcsParams
     # - GET: version-resource-5
      - IN: generate-manifest
      - IN: sample_pipelines_master_rSync
      - TASK: managed
      
  - name: foo4
    type: release
    options:
      action: minor
    steps:
     # - GET: version-resource-4
      - IN: version-resource-3
      - TASK: managed
      - IN: kickStart

  - name: generate-mongo-image-manifest-6
    type: manifest
    steps:
      - IN: myOtherDockerOptions
      - IN: mongo-image
        pull: false
  #    - GET: generate-manifest
  #    - GET: myEcsParams
  #      applyTo:
  #        - image
      
  #    - GET: myOtherEcsParams
#      - GET: deploy-service
  #    - GET: myOtherDockerOptions
  #      applyTo:
  #        - mongo-image
      - TASK: managed

  - name: generate-manifest
    type: manifest
    steps:
      - IN: mongo-image
      - IN: triggerOne
  #    - GET: myReplicas
#      - GET: deploy-service
  #    - GET: myOtherDockerOptions
      - TASK: managed
   

 # - name: deploy-service
#    type: ecsDeploy
#    steps:
#      - GET: generate-mongo-image-manifest-3
#      - GET: myEcsCluster

  - name: deploy-service-7
    type: dclDeploy
    steps:
      - IN: generate-manifest
      - IN: myDclCluster
      - IN: myEcsParams
        applyTo:
          - other
      - IN: myOtherEcsParams
      - IN: foo4
      - TASK: managed

  - name: deploy-dcl
    type: dclDeploy
    steps:
      - IN: generate-manifest
      - IN: myDclCluster
      - IN: myEcsParams
      - IN: myOtherEcsParams
      - IN: triggerTwo
      - TASK: managed
        deployMethod: upgrade
 
  - name: ecs-deploy2
    type: ecsDeploy
    steps:
      - IN: triggerTwo
      - IN: generate-mongo-image-manifest-6
      - IN: myEcsCluster
      - IN: myReplicas
#      - GET: deploy-service-7
#      - GET: myEcsParams
      - IN: myOtherDockerOptions
        applyTo:
          - mongo-image
      - TASK: managed
        deployMethod: blueGreen
        
  - name: gke-deploy
    type: gkeDeploy
    steps:
      - IN: sample_pipelines_master_rSync
      - IN: generate-mongo-image-manifest-6
      - IN: myGKECluster
      - IN: myOtherDockerOptions
        applyTo:
          - mongo-image
      - TASK: managed
        deployMethod: upgrade
 
  #- name: deploy-service-10
  #  type: ecsDeploy
  #  steps:
  #    - GET: generate-mongo-image-manifest-6
  # #   - GET: myEcsCluster
  #    - GET: myOtherDockerOptions
  # #   - GET: myReplicas
  #    - GET: deploy-service-7
  #    - GET: myEcsParams
  #    - GET: triggerTwo
  # #   - GET: myOtherEcsParams

  - name: CI-project
    type: runCI
    steps:
     # - IN: triggerOne
     # - IN: myEcsParams
      - TASK: managed
      - OUT: mongo-image
      - IN: projectToTrigger
