# Language setting
language: python

python:
  - 2.7

build:
  ci:
    - python --version

resources:
  - name: bitbucket-integration-shippable-yml
    type: integration
    integration: bitbucket
    flags: shippable-yml
  - name: test

  - name: trigger-shippable-yml
    type: trigger
    flags: shippable-yml
    version:
      count: I

  - name: rename-repo5
    type: gitRepo
    integration: github
    pointer:
      sourceName: a-murphy/testRename5
      branch: master
      buildOnPullRequest: true
      buildOnPullRequestClose: true
      buildOnCommit: false


  - name: gitlab-repo8
    type: gitRepo
    integration: gitlab
    pointer:
      sourceName: a-murphy/sample_ubuntu1204_go # a-murphy-gitlab-group/group-project # 
  #    sourceUrl: notarealurl
      buildOnPullRequest: true
      buildOnPullRequestClose: true
      branches:
        except:
          - master
     
#  - name: sample_pipelines_master
#    type: syncRepo
#    flags:
#      - one
#      - two
jobs:
  - name: runSh-shippable-yml
    type: runSh
    flags: shippable-yml
    steps:
     - TASK:
        - script: "echo true"
 
  - name: azure_test
    type: runSh        
    steps:
   #   - IN: myAzureCluster
   #   - IN: image-resource
   #   - IN: myLoadBalancer
   #     showBuildStatus: true
      - IN: rename-repo5
   #   - IN: gitlab-repo8
   #   - IN: filenames
      - OUT: testRename5_ciRepo
   #     replicate: gitlab-repo8
    #  - IN: file2
    #    pull: true
      - TASK:
        - script: echo "MYAZURECLUSTER_SOURCENAME $MYAZURECLUSTER_SOURCENAME"
        - script: echo "IMAGERESOURCE_SOURCENAME $IMAGERESOURCE_SOURCENAME"
        - script: echo "MYLOADBALANCER_SOURCENAME $MYLOADBALANCER_SOURCENAME"
