# Language setting
language: python

python:
  - 2.7

build:
  ci:
    - python --version

resources:
  - name: bitbucket-integration-shippable-yml
    type: integration
    integration: bitbucket
    flags: shippable-yml
  - name: test

  - name: trigger-shippable-yml
    type: trigger
    flags: shippable-yml
    version:
      count: I
      
  - name: sample_pipelines_master
    type: syncRepo
    flags:
      - one
      - two: 2
jobs:
  - name: runSh-shippable-yml
    type: runSh
    flags: shippable-yml
    steps:
     - TASK:
        - script: "echo true"
