triggers:
  - name: triggerOne
    type: trigger
    source:
      count: I
      
  - name: triggerTwo
    type: trigger
    source:
      count: I
      
  - name: triggerThree
    type: trigger
    source:
      count: I
