# Language setting
language: python

python:
  - 2.7

build:
  ci:
    - python --version

resources:
  - name: bitbucket-integration-shippable-yml
    type: integration
    integration: bitbucket
    flags: shippable-yml
  - name: test

  - name: trigger-shippable-yml
    type: trigger
    flags: shippable-yml
    version:
      count: I

  - name: rename-repo5
    type: gitRepo
    integration: github
    pointer:
      sourceName: a-murphy/testRename5
      branch: master
      buildOnPullRequest: true
      buildOnPullRequestClose: true
      buildOnCommit: false
      test: $PWD
      test2: $RESOURCE_ID
      test3: $TRIGGERSHIPPABLEYML_VERSIONNUMBER
    version:
      version: $TRIGGERSHIPPABLEYML_VERSIONID


  - name: gitlab-repo8
    type: gitRepo
    integration: gitlab
    pointer:
      sourceName: a-murphy/sample_ubuntu1204_go # a-murphy-gitlab-group/group-project # 
  #    sourceUrl: notarealurl
      buildOnPullRequest: true
      buildOnPullRequestClose: true
      branches:
        except:
          - master
          
  - name: test-repo2
    type: gitRepo
    integration: github
    versionTemplate:
      sourceName: a-murphy/sample_pipelines
      branches:
        except:
          - master
          
  - name: gke_Config_Resource
    type: cliConfig
    integration: gcloud
    pointer:
      clusterName: cluster-1
      namespace: testnamespace
      region: us-central1-a
      
  - name: nodeCluster3
    type: cluster
    integration: Node

#  - name: sample_pipelines_master
#    type: syncRepo
#    flags:
#      - one
#      - two
jobs:
  - name: test-deploy-gitRepo
    type: deploy
    steps:
      - IN: rename-repo5
      - OUT: test-repo2
      - IN: nodeCluster3
      - TASK:
        - script: echo "test"
   
  - name: test-deploy-file
    type: deploy
    steps:
      - IN: file-manifest
      - IN: nodeCluster3
      - TASK:
        - script: echo "test"
        
  - name: test-deploy-both
    type: deploy
    steps:
      - IN: file-manifest
      - IN: rename-repo5
      - IN: nodeCluster3
      - TASK:
        - script: echo "test"
 

  - name: runSh-shippable-yml
    type: runSh
    flags: shippable-yml
    runtime:
      architecture: x86_64		
      os: Ubuntu_14.04
    steps:
     - IN: test-repo2
 #      versionNumber: 5
     - TASK:
        - script: "echo true"
        
  - name: sample_python-1_runCI
    type: runCI
    runtime:
      architecture: x86_64		
      os: Ubuntu_14.04
    steps:
     - IN: test-repo2
  #     versionNumber: 5
        
  - name: CLI_config_test
    type: runCLI
    runtime:
      architecture: x86_64		
      os: CentOS_7
    steps:
      - IN: gke_Config_Resource
      - TASK:
        - script: echo "test"
 
  - name: azure_test
    type: runSh
    runtime:
      architecture: x86_64		
      os: CentOS_7
    steps:
      - IN: gke_Config_Resource
   #   - IN: myAzureCluster
   #   - IN: image-resource
   #   - IN: myLoadBalancer
   #     showBuildStatus: true
      - IN: trigger-shippable-yml
      - IN: rename-repo5
   #   - IN: gitlab-repo8
   #   - IN: filenames
      - OUT: testRename5_ciRepo
   #     replicate: gitlab-repo8
    #  - IN: file2
    #    pull: true
      - TASK:
        - script: shipctl get_resource_version_key rename-repo5 version
        - script: echo "RENAMEREPO5_POINTER_TEST $RENAMEREPO5_POINTER_TEST"
        - script: echo "RENAMEREPO5_POINTER_TEST2 $RENAMEREPO5_POINTER_TEST2"
        - script: echo "RENAMEREPO5_POINTER_TEST3 $RENAMEREPO5_POINTER_TEST3"
        - script: echo "MYAZURECLUSTER_SOURCENAME $MYAZURECLUSTER_SOURCENAME"
        - script: echo "IMAGERESOURCE_SOURCENAME $IMAGERESOURCE_SOURCENAME"
        - script: echo "MYLOADBALANCER_SOURCENAME $MYLOADBALANCER_SOURCENAME"
