jobs:
  #- name: generate-mongo-image-manifest-3
  #  type: manifest
  #  steps:
  #    - GET: mongo-image
  #    - GET: myEcsParams
  
  #- name: thirdExtraRelease
  #  type: release
  #  steps:
  #    - IN: generate-manifest
  #    - TASK: managed

  - name: foo
    type: release
    options:
      action: test
    on_start:
      - NOTIFY: emailMe
      - NOTIFY: notifyMe
    steps:
      - IN: triggerTwo
    #  - IN: sample_pipelines_master_rSync
    #  - IN: time
      - IN: version-resource-1
     # - GET: myEcsParams
     # - GET: version-resource-5
      - IN: generate-manifest
      - TASK: managed
    on_success:
   #    - test1
  #     - test2
       - NOTIFY: notifyMe
  #  on_failure:
  #     - test
    #   - NOTIFY: notifyMe
    #   - NOTIFY: emailMe
      
      
  - name: foo5
    type: release
    steps:
#      - IN: version-resource-1
#     # - GET: myEcsParams
#     # - GET: version-resource-5
       - IN: generate-manifest
         switch: off
         versionNumber: x
#      - IN: sample_pipelines_master_rSync
       - TASK: managed
      
  - name: foo4
    type: release
    options:
      action: patch
    steps:
     # - GET: version-resource-4
      - IN: deploy-dcl-2
#      - IN: myReplicas
      - IN: version-resource-1
      - TASK: managed

  - name: generate-mongo-image-manifest-6
    type: manifest
    steps:
    #  - IN: myOtherDockerOptions
      - IN: customImage
        switch: off
 #     - IN: triggerOne
      - IN: new-mongo-image
        pull: false
        switch: off
      - IN: generate-manifest
        switch: off
  #    - GET: generate-manifest
  #    - GET: myEcsParams
  #      applyTo:
  #        - image
      
  #    - GET: myOtherEcsParams
#      - GET: deploy-service
  #    - GET: myOtherDockerOptions
  #      applyTo:
  #        - mongo-image
      - TASK: managed

  - name: generate-manifest
    type: manifest
    steps:
      - IN: mongo-image
        switch: off
   #   - OUT: triggerOne
   
   #   - GET: myReplicas
  #    - GET: deploy-service
      - IN: myDockerOptions
      - TASK: managed
      
  - name: ecr-manifest
    type: manifest
    steps:
      - IN: ecr-image
        switch: off
      - IN: myDockerOptions
      - TASK: managed
   
  - name: nginx-manifest
    type: manifest
    steps:
      - IN: nginx-image
        switch: off
      - IN: gitlabProject
      - TASK: managed
      
     
  - name: busybox-manifest
    type: manifest
    steps:
      - IN: branchlessProject3
      - IN: busybox-image
        switch: off
      - TASK: managed
   
  - name: nginx-and-busybox-manifest
    type: manifest
    steps:
      - IN: nginx-manifest
        switch: off
      - IN: busybox-manifest
        switch: off
      - IN: bitbucketProject2
      - TASK: managed
   
  - name: new-manifest
    type: manifest
    steps:
      - IN: mongo-manifest
      - IN: busybox-manifest
      - TASK: managed

 # - name: deploy-service
#    type: deploy
#    steps:
#      - IN: generate-mongo-image-manifest-6
#      - IN: myEcsCluster

  - name: deploy-service-7
    type: deploy
    steps:
      - IN: generate-manifest
        switch: off
      - IN: myDclCluster
 #     - IN: myEcsParams
#        applyTo:
#          - other
      - IN: myOtherEcsParams
      - IN: foo4
      - TASK: managed

  - name: deploy-dcl-2
    type: deploy
    steps:
 #     - IN: generate-manifest
 #       switch: on
      - IN: myDclCluster
  #   - IN: myEcsParams
      - IN: myOtherEcsParams
      - IN: myOtherDockerOptions
      - TASK: managed
        deployMethod: upgrade
 
  - name: new-ecs-deploy
    type: deploy
    steps:
    #  - IN: foo4
     # - IN: generate-mongo-image-manifest-6
    #  - IN: foo
      - IN: generate-manifest
      - IN: nginx-image
     # - IN: nginx-and-busybox-manifest
     # - IN: new-manifest
      - IN: myLoadBalancer
        applyTo:
          - manifest: generate-manifest
            image: mongo-image
            port: 27017
      - IN: ecs-deploy2
      - IN: myEcsCluster
      - IN: myReplicas
#      - GET: deploy-service-7
#      - GET: myEcsParams
      - IN: myOtherDockerOptions
        applyTo:
          - mongo-image
     #     - nginx-image
      - TASK: managed
     #   deployMethod: upgrade
     
  - name: replace-ecs-deploy2
    type: deploy
    steps:
      - IN: generate-manifest
      - IN: nginx-image
      - IN: myEcsCluster
      - TASK: managed
        deployMethod: replace

  - name: replace-ecs-deploy
    type: deploy
    steps:
      - IN: generate-manifest
      - IN: nginx-image
  #    - IN: myLoadBalancer
  #      applyTo:
  #        - manifest: generate-manifest
  #          image: mongo-image
  #          port: 27017
      - IN: myEcsCluster
      - IN: myOtherDockerOptions
        applyTo:
          - mongo-image
      - TASK: managed
        deployMethod: replace
        
  - name: replace-triton-deploy
    type: deploy
    steps:
      - IN: ecr-manifest
        switch: off
      - IN: tritonCluster
      - IN: myReplicas
      - IN: myOtherDockerOptions
      - TASK: managed
        deployMethod: replace

  - name: new-ecs-deploy-again
    type: deploy
    steps:
      - IN: new-ecs-deploy
        switch: off
      - IN: myEcsCluster
      - TASK: managed
        deployMethod: upgrade

  - name: ecs-deploy2
    type: deploy
    steps:
      - IN: myEcsCluster
      - IN: generate-manifest
    #  - OUT: gke-deploy
     # - IN: myReplicas
#      - GET: deploy-service-7
    #  - GET: myEcsParams
      - IN: myOtherDockerOptions
     #   applyTo:
      #    - mongo-image
      - TASK: managed
        deployMethod: upgrade
        
  - name: gke-deploy
    type: deploy
    steps:
      - IN: generate-mongo-image-manifest-6
      - IN: myGKECluster
      - IN: myOtherDockerOptions
        applyTo:
          - mongo-image
      - IN: myThirdDockerOptions
 #       applyTo:
 #         - nginx-image
      - TASK: managed
        deployMethod: blueGreen
        
 # - name: empty-deploy
 #   type: deploy
 #   steps:
    
 # - name: new-empty-deploy
 #   type: deploy

  - name: customImage
    type: runSh
    steps:
      - TASK:
        - script: "mkdir -p /build/state/"
        - script: "touch /build/state/mongo-image.env"
        - script: "echo 'versionName=latest' >>  /build/state/mongo-image.env"
        - script: "echo 'anotherProperty=foo' >>  /build/state/mongo-image.env"
        - script: "echo 'anotherProperty2=foo2' >>  /build/state/mongo-image.env"
      - OUT: mongo-image
      
  - name: custom3
    type: runSh
    steps:
      - IN: customImage
      - IN: pipelines-dv-image
      - TASK:
        - script: "ls /build/IN/customImage"
      
  - name: custom2
    type: runSh
    steps:
      - IN: gitlabProject
        versionNumber: 4
      - IN: time
      - TASK:
        - script: "ls -al /build/IN/gitlabProject/gitRepo"
        
  - name: custom5
    type: runSh
    steps:
      - IN: ecr-image
      - TASK:
        - script: "apt-get install unzip"
        - script: 'curl -s "https://s3.amazonaws.com/aws-cli/awscli-bundle.zip" -o "awscli-bundle.zip"'
        - script: "unzip awscli-bundle.zip"
        - script: "./awscli-bundle/install -i /usr/local/aws -b /usr/local/bin/aws"
        - script: "chmod +x /build/IN/ecr-image/integration.env"
        - script: ". /build/IN/ecr-image/integration.env"
        - script: "dockerLogin=$(AWS_ACCESS_KEY_ID=$aws_access_key_id AWS_SECRET_ACCESS_KEY=$aws_secret_access_key aws ecr get-login --region us-west-2)"
        - script: "$dockerLogin"
        - script: "cat /build/IN/ecr-image/version.json"
        - script: "docker pull $(cat /build/IN/ecr-image/version.json | jq '.sourceName'):$(cat /build/IN/ecr-image/version.json | jq '.version.versionName')"
        
  - name: custom4
    type: runSh
    steps:
      - IN: privateProject3
      - OUT: pipelines-dv-image
      - TASK:
        - script: "ls -al /build/IN/privateProject3/gitRepo"

 # - name: CI-project
 #   type: runCI
 #   steps:
 #    # - IN: triggerOne
 #    # - IN: myEcsParams
 #     - IN: projectOne
 #     - TASK: managed
 #     - OUT: mongo-image

