# Language setting
language: python

python:
  - 2.7

build:
  ci:
    - python --version

resources:
  - name: testParamsValue
    type: params
    versionTemplate:
      params:
   #     secure: AYgkVcr+hwoqDnHDCzHrkePBCTyDx249LqX+3XO6w4pVi54QBDO9PneuDBA2Py9fbjB7q2JwzJZy3zsfY1eNO5DjSaAnXBl3CJVrMySJPXhaXHaWAhVXZ3G7agz0Y3hyByAeIJx3ozvZlq1Ky3WH5k08rkrUP9zMYxxH8tNOCT/wUnFwFSn64axuWfzoDWpfhzfM86UhspW8/4FgYuAirSmLyYYvUfELh9zUNrNkP0aBGLMgTMb97unqVqaLEWoOzu4p1q/EMa4kJ3541Wqa24EtSN/b+FRRuOZWFb4JlK5WyHtvuc1juOheVoEzXdLMWsdJeGO8HfO/8GBx0o8fNg== 
   #     secure: hM5vTNW21fHHdr1cgZkUywyL1azcSGHXDLQ8YPz571WrnGLR/jD+RojMfccvZVukMyGJ22r6xJqh0VKanhH0O/Tx4V3CdqLuszPulZzGSV2dSToD/fqu8vRiREKEa78dOW8ZFXKrL8x0+PcxdbUYaHFEpg8a11hLJSozsxoXwsNxVFzz95yiNT0szMNkBlY06xTNtGPl8SdVvrJwnDGV+sA/PNsGHVrQlBxpz7xQvz4Mk72rtXIDIGYz26WdCs4Fh2VW64msEOC7d8RhhSDRXYhJsTDfAW7tjkhz3KOpX5ffE7QFzisaThXKXNOpdjtGTXjjqb/aa0AgQ6ATtKT0RQ==
   #     secure: e9h6nzFJXx/bN5GABL05bDeX0d/v5VOEYRJfb2bvkNSBScf9GxUq4C+Jz/wnrolNEl/5Sfa4eP7YaIqENrWgau7gkDKkut6JlAxVdMRRq9quJ+mqYyt8ldtKsDuxALCOkDuFr3utf+xQBhjMe1Fp45d8PCNVnpaIZV0goV0XAA1UWq4NEiMA5iwrnjzyshuZTTFZU/z0QbXv2F/Xiuz1aNcEBCcCT1lTyeCHpG9gxWFtFfHLDANLiyFeSXmLHoW+DjQfmBnRyVhGxpObSGErz2EZI6/GsekBSXTVIo27LaNJsfYjdMK1APERsE5qyrxUohIk8oblDhDxg50B8iKACw==
   #     secure: eFfiCn4crCi30o75BBSyPVrLFAuwwL5B/77fI6tPgFOFv5Yx9n24UhJiBN085WiWPgwMhitgHrAyY8am4eGbPpSJdtXejOQb7mhX4QstOxtf2EAgkNo3gmQ3+j4Iu0g06xgidjcLCLTRM6uoFvo2pi/nOHOGxDJd2zizOF9L5flsuvCYZrwCB3XKNWY7OEuhJeifBsotF3WnDhgbwAgzX4BvtwDHJhCPeqKnzYOfmv1YqSIwguMGnaDhXIOSIdYnj9yUXkdBcdVLh4VAgzyUIfEP+w4RBqQuG6hH5C9iTD3osDXIcF8jGGCHK+9fjKmiB7yB2oyWkcHTfOp78BAnKA==
   #     secure: iVtClVrxqVOMfZpx2Yinq5zI9w+gpXkNREZBeM9l9WRcYWT4H4dyCFu+x98rR7ErjVwBm3VLxfZVjTzQc98aRuJC6QRrVqXiNG5LrJNQXy16TQ4/rVegWFwtsWW2lVtGwfjAwelE4kTN6Pp4KSot2F1YfxnbrVGYhq3xKLGMMkxauG8K2DdEjBDaIzDy0ce8E+JTzo5j7mXFuxrTomx0V41ChQdS/Kh9QwyGZkMlLn5Ar//kZ8DapiEh2GzQPODw1qYNM152Sk3RoV6A2uA/QzL0A5JkcKVLA0VfO5PBErTYumLFW25tQW2qCkh/EmCVIZQc121hfivSkumivdTdhQ==
   #     secure: CM5FL8hUxnX8P7jxlkIBLGklNm6gcAyOB2XRuwdVWgQcJrNP4JORTY+vfvdlAQiWwDEZ4ZiZYgxyFRcsVtAkY5l7y0G092EfqZ9gmGLxa7YYIXDgR5OCjPGVKI7lfjcAarjFB1bOvW0LqF6UxW3Gsxxuhq1DkT/+PSOrGTSCeSOOuRRisp4UiNJPtDkS+Fg4z38zON/7GsLI7kvPMjlFAoQxyhrqLvMn6C60BEqTVUggYYFpGfVY+RMpACP/XBD/OT9nAXdkkJNARsiEiAyAOsZXR1o43ekXuIBuGMj8SGfwVWzYnF7PZQcJb+zLYbSCOh6DxZyaM3X8zKGp9PLJbQ==
   #     secure: SBdClN2QpV8omc6jKiM5EmYWobozrkng7OMsuq0HXm1olQ6HwY+fv8Hv5bBvJe7X7wMS7IEKCZvdN9911DOT8loXxved7Eh5afn/ytkQAIVNCxA/H9tJYXPGBOeWxLZNQ2UOcMH6J1afpwzvUPkT7nzkLNN8aPiFr8HGNwcy/SALhcTcIU2+PBSUiMcwcn7AKhmR11psjMwIe737zt7e+sh7GgoVFQVxHF0VJehFIUofUbEsvhV5M0s3fVinTyMG6xUl9Yv2SDp0xadKDXesB9Y4eDFn/4PVU//M3kev5kCckmgyJOWeboRWgBOI8n9pe1BwGeWzbNDvg4voY/DoXQ==
   #     secure: iKEupHAV89GzM0Kdq6+31MA4zREDK8EsX3Ka4cwfHsd4lUVdvDZdYjJFGOOeTCQOM3f9u4h+/xJC1/019f2Tt+uAv1vK290/LXVbMIDEIAk0lGKZuiz/bGSh8nwmK61iYdiUepZKGISMLN3P4Xy8i6izTrqq0ZHsU6Ef2DViI0OmBTwEO+JO4QBJVyLjeXsubYd2ee4hBadzCQFk+JlHQYwlFxUt6Si8wDmStRVOLWnPSG8SRL3Z8cUDSrV/u9ziIZyhK/ER2MAQpl1t2JFHtm9KJ+P62+zR/voCv3o+qjjlhaLxULaZlRMFGePDri/imbNtrAchf+G+PSH5hCBPZg==
   #     secure: U8rcqLY6JFGT644AEX6EnZ7XZmCoEFkkdwsbpIU/85FPv45SAvjwWTRhFHeIMn6BNYsXzwhE8H7Rkz5Fzlsb+phaCR4bHA5Z1WQgJ8DZRITM4Fu/ldOmeJCJeNfUJe+2kIwHWKql1KXzS8t97/CLFKh3TK5YgtjdfX8Q3f9HEdBwugWL3I74U1PMcu5N60yLh2cwC6T1O1ar/xkpPlA1/kKf4ClKOeuNS16Z8lO3rplEERFnOtLiEL6+UAqQ2hq/zoIBxFjsZoaMC+GI0WcefcSsU+KDUpaOsRJRxnU3E1W2uOxlmk2s0gerMNNjuZOW49lsOcWrSxD3Bwc6KiuLtQ==\
   #     secure: TD+lTzaXjc5XystFa2RSxh7IVDfzE28wpUsa6Ve6G/ly2OpuuqjZPNEwdxd+5w8EiVt2UgjuMQArmt1RHS5gpgh0A0WriAXCBdyamNtd1RluUURqQk9/PfWRkmft0yeTTO7Jjl9T/VMPaYwUNyR0qQBXTsuzm99yCE3Oos+X5CBjvGrO1BuV2lLgYbKKpujCAUbO73gY5rFhooZwV+loz73ZFw9GFjKa/y8ZvS+DYmdJ9Z+IUfiw8tFYJSqj901/3UYIf/3Z4gc3VO/2DvB5Vtp3/Ps5hQuempmnr8jt5i1t2ik3SoOAl924Vi1NzvU3jMknKLoAzNCD5wdC7ACFPg==
        secure: fzBkW713QsBYv+ue7Rj12KEiQNaeFHPa8aU855o0LBOcGePWm/aEvp1GTf749+7PHDEm5d0F1bqUU1+emW1iqZ+JlfiEjLIx9LkGRu9dX2A+0fU/gx/wKzFQAaw3OK+p209DBxZlpbA/Q3Fqc305TOvXzoM7w6xvS8gpfnKNvBjWYZHlRQGfSWp6JHiV/j14x1Eu72DX4LLwcWV5ln4A58ZN5TWPAr62Mpuim4+FKa/IB9jdCXRLqd5sHnj6AZLtLstQrldP/bbjLWmXQf1PaPrA9Q8FXvkU6wm0zsOEdLNhnj90goUF/SIFCp1H7ZySnnlZ6k1uTDlFMGexB7eatQ==
   #     secure: A7PVHrim6FzpZZofWlVVZGVFieHbe/BS6qoKHhjPn6D+8PxSmPCWdN2CeUCjB2E6eIBBCcRp+m1RQtzIvFRYYKEkj96UNg3Hlm4oSAj9lX85SrnrJcpV7rlvQkpHr5FyzE1aJZh8MRMil/lZPSJMNhOi/JawoJ4joJ7ayferxZf7jEYMbwt5ulMx17cr1QWSgoaPejUEFB04DTGbZeccjNzARGR20pXj6MAw732wUoppAGBE2HJAzc/1iG/29f0au2l3r1tGGclbyBuOvnukzKRJMaAgrf3fAqhtmU/691ebNUXOwoS6v3MkXIWYQ5kQ6nsl1ydDuES/lQ6JQqlP4Q==


  - name: paramsTest
    type: integration
    integration: testValue
      
  - name: test-image
    type: image
    pointer:
      sourceName: 544102397216.dkr.ecr.us-west-2.amazonaws.com/test/repository
    version:
      versionName: latest
      
  - name: 123_numbers
    type: image
    versionTemplate:
      sourceName: busybox
      versionName: latest
      
  - name: 123-testing-123
    type: image
    versionTemplate:
      versionName: $_NUMBERS_VERSIONNAME
      sourceName: $_FILEMANIFEST_NAME

  - name: 123-params
    type: params
    versionTemplate:
      params:
  #      123test: testing
        empty: ""

  - name: bitbucket-integration-shippable-yml
    type: integration
    integration: bitbucket
    flags: shippable-yml

  - name: trigger-shippable-yml
    type: trigger
    flags: shippable-yml
    version:
      count: I

  - name: rename-repo5
    type: gitRepo
    integration: github
    pointer:
      sourceName: a-murphy/testRename5
      branch: master
      buildOnPullRequest: true
      buildOnPullRequestClose: true
      buildOnCommit: false
      test: $PWD
      test2: $RESOURCE_ID
      test3: $TRIGGERSHIPPABLEYML_VERSIONNUMBER
    version:
      version: $TRIGGERSHIPPABLEYML_VERSIONID


  - name: gitlab-repo8
    type: gitRepo
    integration: gitlab
    pointer:
      sourceName: a-murphy/sample_ubuntu1204_go # a-murphy-gitlab-group/group-project # 
  #    sourceUrl: notarealurl
      buildOnPullRequest: true
      buildOnPullRequestClose: true
      branches:
        except:
          - master
          
  - name: test-repo2
    type: gitRepo
    integration: github
    versionTemplate:
      sourceName: a-murphy/sample_pipelines
      buildOnPullRequest: true

  - name: gke_Config_Resource
    type: cliConfig
    integration: gcloud
    pointer:
      clusterName: cluster-1
      namespace: testnamespace
      region: us-central1-a
      scopes:
          - gke
          - gcr
                
  - name: awsKeysCliConfig
    type: cliConfig
    integration: awsKeys
    pointer:
      region: us-west-2
      scopes:
        - ecr
      
  - name: nodeCluster3
    type: cluster
    integration: Node
    
  - name: gcloudKeysCluster
    type: cluster
    integration: gcloud
    versionTemplate:
      sourceName : "cluster-1"
      region: "us-central1-a"
      namespace: mynamespace
      
  - name: newReplicas
    type: replicas
    versionTemplate:
      count: 0
      minReplicas: 0
      maxReplicas: 1
  #    autoScalingRole: role
      autoScalingPolicies:
        - PolicyName: testPolicy
          PolicyType: "StepScaling"
          StepScalingPolicyConfiguration:
            AdjustmentType: "PercentChangeInCapacity"
            Cooldown: 60
            StepAdjustments:
              - MetricIntervalLowerBound: 0
                ScalingAdjustment: 150
         
        - PolicyName: testTargetPolicy
          PolicyType: "TargetTrackingScaling"
          TargetTrackingScalingPolicyConfiguration:
            TargetValue: 0.5
            PredefinedMetricSpecification:
              PredefinedMetricType: ECSServiceAverageCPUUtilization
            DisableScaleIn: false
            ScaleInCooldown: 0
            ScaleOutCooldown: 0

      metricAlarms:
        - AlarmName: "my-alarm"
          ComparisonOperator: "GreaterThanThreshold"
          EvaluationPeriods: 2
          MetricName: "high-cpu"
          Namespace: "test"
          Statistic: Average 
          Period: 60
          Threshold: 75.0
          AlarmActions:
            - testPolicy
                
  - name: otherPolicy
    type: replicas
    versionTemplate:
      count: 0
      autoScalingPolicies:
        - PolicyName: testPolicy2
          PolicyType: "StepScaling"
          StepScalingPolicyConfiguration:
            AdjustmentType: "PercentChangeInCapacity"
            Cooldown: 60
            StepAdjustments:
              - MetricIntervalLowerBound: 0
                ScalingAdjustment: 200
      

jobs:
  - name: myRunSh
    type: runSh
    steps:
     - IN: testParamsValue
     - TASK:
         script:
           - echo $SHIPPABLE_RELEASE_VERSION
           - echo $SHIPPABLE_AMI_VERSION
           - echo $TEST_ONE
           - echo $TEST_TWO
           - echo $TEST_THREE
           - echo $TESTPARAMSVALUE_PARAMS_TEST_ONE
           - echo $TESTPARAMSVALUE_PARAMS_TEST_TWO
           - echo $TESTPARAMSVALUE_PARAMS_TEST_THREE
           - Get-Item "env:$TEST_ONE"
           - Get-Item "env:$TEST_TWO"
           - Get-Item "env:$TEST_THREE"
    on_success:
      - NOTIFY: emailMe
   #     sendFailingSnippet: true
    on_failure:
      script:
        - echo "FAILED"
      NOTIFY: emailMe
    #  - NOTIFY: emailMeTwo
    #    sendFailingSnippet: true
    on_start:
       NOTIFY: emailMe
   #    sendFailingSnippet: true
   #   - NOTIFY: notifyMe
    on_cancel:
      - NOTIFY: emailMe
   #     sendFailingSnippet: true

  - name: 123-runSh-123
    type: runSh
    runtime:
      architecture: x86_64		
      os: Ubuntu_14.04
    steps:
     - IN: testValue
     - IN: 123_numbers
     - IN: 123_file-manifest
     - IN: 5testRename5_runCI
     - IN: 123-testing-123
     - IN: file-manifest
     - IN: gke_Config_Resource
     - IN: bitbucket-integration-shippable-yml
     - TASK:
        - script: ls -al ~/.ssh
        - script: aws --version
        - script: "echo $runId"
        - script: "echo true"
        - script: "echo 123_numbers path: $_NUMBERS_PATH"
        - script: "echo 123_file-manifest path: $_FILEMANIFEST_PATH"
        - script: sleep 15
        
  - name: 5testRename5_runCI
    type: runCI
    runtime:
      architecture: x86_64		
      os: Ubuntu_14.04
    steps:
     - IN: testParamsValue
     - IN: 123_numbers
 #    - IN: 123-params
     - IN: 5testRename5_ciRepo
     - OUT: 123-testing-123
     
  - name: test_runSh
    type: runSh
    runtime:
      - nodePool: aidans-test-pool 
#      architecture: x86_64		
#      os: Ubuntu_14.04
    steps:
     - IN: 123_numbers
     - IN: 123-params
     - IN: azureConfig
     - IN: 5testRename5_ciRepo
     - TASK:
       - script: echo test
        
  - name: file-manifest
    type: manifest
    steps:
      - IN: file

  - name: 123_file-manifest
    type: manifest
    steps:
      - IN: 123-params
      - IN: file
      - IN: 123_numbers
      - IN: 123-testing-123
      
  - name: test-manifest
    type: manifest
    steps:
      - IN: test-image
      - IN: testParamsValue
 
  - name: test-deploy-gitRepo
    maxWaitTime: 40000
    type: deploy
    steps:
      - IN: rename-repo5
  #    - OUT: test-repo2
      - IN: nodeCluster
      - IN: 123_numbers
      - TASK:
        - script: echo "test"
        - script: ls /tmp/shippable
        - script: cat /tmp/shippable/rename-repo5/gitRepo/shippable.yml
   
  - name: test-deploy-file
    type: deploy
    maxWaitTime: 300
    steps:
      - IN: file-manifest
      - IN: nodeCluster3
      - TASK:
        - script: echo "test"
        
  - name: test-deploy-both
    type: deploy
    steps:
      - IN: file-manifest
      - IN: rename-repo5
      - IN: nodeCluster
      - TASK:
        - script: echo "test"
        
  - name: bluegreen-deploy
    type: deploy
    method: blueGreen
    stabilityDuration: 30
    steps:
   #   - IN: test-manifest
      - IN: nginx-manifest3
   #   - IN: busybox-manifest2 
      - IN: awsKeysCluster
      - IN: zeroReplicas
        versionNumber: 1
      - IN: newReplicas
        applyTo:
          - none
          - nginx-manifest3
   #       - busybox-manifest2 

  - name: replace-deploy
    type: deploy
    method: replace
    maxWaitTime: 30
    steps:
      - IN: test-manifest
   #   - IN: nginx-manifest3
  #    - IN: busybox-manifest2 
      - IN: awsKeysCluster
  #   - IN: myLoadBalancer
  #      applyTo:
  #        - manifest: nginx-manifest3
  #          image: nginx-image
  #          port: 27017
  #    - IN: myOtherDockerOptions
  #- IN: zeroReplicas
 #       versionNumber: 1
      - IN: newReplicas
  #      applyTo:
  #        - none
  #        - manifest: nginx-manifest3
        
  - name: upgrade-deploy
    type: deploy
    method: upgrade
    steps:
   #   - IN: test-manifest
      - IN: nginx-manifest3
      - IN: awsKeysCluster
#      - IN: myLoadBalancer
#        applyTo:
#          - manifest: nginx-manifest3
#            image: nginx-image
#            port: 27017
      - IN: myOtherDockerOptions
      - IN: zeroReplicas
        versionNumber: 1
  #    - IN: otherPolicy
      - IN: newReplicas
        applyTo:
          - none
   #       - manifest: nginx-manifest3


  - name: runSh-shippable-yml
    type: runSh
    flags: shippable-yml
    runtime:
      architecture: x86_64		
      os: Ubuntu_14.04
    steps:
     - IN: test-repo2
 #      versionNumber: 5
     - TASK:
        - script: sleep 400
        - script: "echo true"
        
        
  - name: runSh-object
    type: runSh
    flags: shippable-yml
    runtime:
      architecture: x86_64		
      os: Ubuntu_14.04
    steps:
     - IN: test-repo2
 #      versionNumber: 5
     - TASK:
         script:
           - "echo true"
        
  - name: runSh-no-task
    type: runSh
    flags: shippable-yml
    runtime:
      architecture: x86_64		
      os: Ubuntu_14.04
    steps:
     - IN: test-repo2

  - name: CLI_config_test
    type: runCLI
    runtime:
      architecture: x86_64		
      os: CentOS_7
    steps:
      - IN: gke_Config_Resource
      - TASK:
        - script: echo "test"
 
  - name: azure_test
    type: runSh
    runtime:
      architecture: x86_64		
      os: CentOS_7
    steps:
      - IN: gke_Config_Resource
   #   - IN: myAzureCluster
   #   - IN: image-resource
      - IN: trigger-shippable-yml
      - IN: rename-repo5
      - TASK:
        - script: shipctl get_resource_version_key rename-repo5 version
        - script: echo "RENAMEREPO5_POINTER_TEST $RENAMEREPO5_POINTER_TEST"
        - script: echo "RENAMEREPO5_POINTER_TEST2 $RENAMEREPO5_POINTER_TEST2"
        - script: echo "RENAMEREPO5_POINTER_TEST3 $RENAMEREPO5_POINTER_TEST3"
