# Language setting
language: python

python:
  - 2.7

build:
  ci:
    - python --version

resources:
  - name: testParamsValue
    type: params
    versionTemplate:
      params:
   #     secure: AYgkVcr+hwoqDnHDCzHrkePBCTyDx249LqX+3XO6w4pVi54QBDO9PneuDBA2Py9fbjB7q2JwzJZy3zsfY1eNO5DjSaAnXBl3CJVrMySJPXhaXHaWAhVXZ3G7agz0Y3hyByAeIJx3ozvZlq1Ky3WH5k08rkrUP9zMYxxH8tNOCT/wUnFwFSn64axuWfzoDWpfhzfM86UhspW8/4FgYuAirSmLyYYvUfELh9zUNrNkP0aBGLMgTMb97unqVqaLEWoOzu4p1q/EMa4kJ3541Wqa24EtSN/b+FRRuOZWFb4JlK5WyHtvuc1juOheVoEzXdLMWsdJeGO8HfO/8GBx0o8fNg== 
        a: "$b=$c"
        a2: '"$b\=$c"'
        a3: '"$b"="$c"'
        a4: $b=$c
        a5: $b"="$c
        a7: '"$b=$c"'
    
  - name: paramsTest
    type: integration
    integration: testValue
      
  - name: test-image
    type: image
    pointer:
      sourceName: 544102397216.dkr.ecr.us-west-2.amazonaws.com/test/repository
    version:
      versionName: latest
      
  - name: 123_numbers
    type: image
    versionTemplate:
      sourceName: busybox
      versionName: latest
      
  - name: 123-testing-123
    type: image
    versionTemplate:
      versionName: $_NUMBERS_VERSIONNAME
      sourceName: $_FILEMANIFEST_NAME

  - name: 123-params
    type: params
    versionTemplate:
      params:
  #      123test: testing
        empty: ""

  - name: bitbucket-integration-shippable-yml
    type: integration
    integration: bitbucket
    flags: shippable-yml

  - name: trigger-shippable-yml
    type: trigger
    flags: shippable-yml
    version:
      count: I

  - name: rename-repo5
    type: gitRepo
    integration: github
    pointer:
      sourceName: a-murphy/testRename5
      branch: master
      buildOnPullRequest: true
      buildOnPullRequestClose: true
      buildOnCommit: false
      test: $PWD
      test2: $RESOURCE_ID
      test3: $TRIGGERSHIPPABLEYML_VERSIONNUMBER
    version:
      version: $TRIGGERSHIPPABLEYML_VERSIONID


  - name: gitlab-repo8
    type: gitRepo
    integration: gitlab
    pointer:
      sourceName: a-murphy/sample_ubuntu1204_go # a-murphy-gitlab-group/group-project # 
  #    sourceUrl: notarealurl
      buildOnPullRequest: true
      buildOnPullRequestClose: true
      branches:
        except:
          - master
          
  - name: test-repo2
    type: gitRepo
    integration: github
    versionTemplate:
      sourceName: a-murphy/sample_pipelines
      buildOnPullRequest: true

  - name: gke_Config_Resource
    type: cliConfig
    integration: gcloud
    pointer:
      clusterName: cluster-1
      namespace: testnamespace
      region: us-central1-a
      scopes:
          - gke
          - gcr
                
  - name: awsKeysCliConfig
    type: cliConfig
    integration: awsKeys
    pointer:
      region: us-west-2
      scopes:
        - ecr
      
  - name: nodeCluster3
    type: cluster
    integration: Node
    
  - name: gcloudKeysCluster
    type: cluster
    integration: gcloud
    versionTemplate:
      sourceName : "cluster-1"
      region: "us-central1-a"
      namespace: mynamespace
      
  - name: newReplicas
    type: replicas
    versionTemplate:
      count: 0
      minReplicas: 0
      maxReplicas: 1
  #    autoScalingRole: role
      autoScalingPolicies:
        - PolicyName: testPolicy
          PolicyType: "StepScaling"
          StepScalingPolicyConfiguration:
            AdjustmentType: "PercentChangeInCapacity"
            Cooldown: 60
            StepAdjustments:
              - MetricIntervalLowerBound: 0
                ScalingAdjustment: 150
         
        - PolicyName: testTargetPolicy
          PolicyType: "TargetTrackingScaling"
          TargetTrackingScalingPolicyConfiguration:
            TargetValue: 0.5
            PredefinedMetricSpecification:
              PredefinedMetricType: ECSServiceAverageCPUUtilization
            DisableScaleIn: false
            ScaleInCooldown: 0
            ScaleOutCooldown: 0

      metricAlarms:
        - AlarmName: "my-alarm"
          ComparisonOperator: "GreaterThanThreshold"
          EvaluationPeriods: 2
          MetricName: "high-cpu"
          Namespace: "test"
          Statistic: Average 
          Period: 60
          Threshold: 75.0
          AlarmActions:
            - testPolicy
                
  - name: otherPolicy
    type: replicas
    versionTemplate:
      count: 0
      autoScalingPolicies:
        - PolicyName: testPolicy2
          PolicyType: "StepScaling"
          StepScalingPolicyConfiguration:
            AdjustmentType: "PercentChangeInCapacity"
            Cooldown: 60
            StepAdjustments:
              - MetricIntervalLowerBound: 0
                ScalingAdjustment: 200
      

jobs:
  - name: myRunSh
    type: runSh
    steps:
     - IN: testParamsValue
     - TASK:
       - script: docker images && fail
       - script: fail
    on_success:
      - NOTIFY: emailMe
   #     sendFailingSnippet: true
    on_failure:
      NOTIFY: emailMe
    #  - NOTIFY: emailMeTwo
    #    sendFailingSnippet: true
    on_start:
       NOTIFY: emailMe
   #    sendFailingSnippet: true
   #   - NOTIFY: notifyMe
    on_cancel:
      - NOTIFY: emailMe
   #     sendFailingSnippet: true

  - name: 123-runSh-123
    type: runSh
    runtime:
      architecture: x86_64		
      os: Ubuntu_14.04
    steps:
     - IN: testValue
     - IN: 123_numbers
     - IN: 123_file-manifest
     - IN: 5testRename5_runCI
     - IN: 123-testing-123
     - IN: file-manifest
     - IN: gke_Config_Resource
     - IN: bitbucket-integration-shippable-yml
     - TASK:
        - script: ls -al ~/.ssh
        - script: aws --version
        - script: "echo $runId"
        - script: "echo true"
        - script: "echo 123_numbers path: $_NUMBERS_PATH"
        - script: "echo 123_file-manifest path: $_FILEMANIFEST_PATH"
        - script: sleep 15
        
  - name: 5testRename5_runCI
    type: runCI
    runtime:
      architecture: x86_64		
      os: Ubuntu_14.04
    steps:
     - IN: 123_numbers
 #    - IN: 123-params
     - IN: 5testRename5_ciRepo
     - IN: azureConfig
     - IN: generate-manifest
       switch: off
     - OUT: 123-testing-123
     
  - name: test_runSh
    type: runSh
    runtime:
      - nodePool: aidans-test-pool 
#      architecture: x86_64		
#      os: Ubuntu_14.04
    steps:
     - IN: 123_numbers
     - IN: 123-params
     - IN: azureConfig
     - IN: 5testRename5_ciRepo
     - TASK:
       - script: echo test
        
  - name: file-manifest
    type: manifest
    steps:
      - IN: file

  - name: 123_file-manifest
    type: manifest
    steps:
      - IN: 123-params
      - IN: file
      - IN: 123_numbers
      - IN: 123-testing-123
      
  - name: test-manifest
    type: manifest
    steps:
      - IN: test-image
 
  - name: test-deploy-gitRepo
    maxWaitTime: 40000
    type: deploy
    steps:
      - IN: rename-repo5
  #    - OUT: test-repo2
      - IN: nodeCluster
      - IN: 123_numbers
      - TASK:
        - script: echo "test"
        - script: ls /tmp/shippable
        - script: cat /tmp/shippable/rename-repo5/gitRepo/shippable.yml
   
  - name: test-deploy-file
    type: deploy
    maxWaitTime: 300
    steps:
      - IN: file-manifest
      - IN: nodeCluster3
      - TASK:
        - script: echo "test"
        
  - name: test-deploy-both
    type: deploy
    steps:
      - IN: file-manifest
      - IN: rename-repo5
      - IN: nodeCluster
      - TASK:
        - script: echo "test"
        
  - name: bluegreen-deploy
    type: deploy
    method: blueGreen
    stabilityDuration: 30
    steps:
   #   - IN: test-manifest
      - IN: nginx-manifest3
   #   - IN: busybox-manifest2 
      - IN: awsKeysCluster
      - IN: zeroReplicas
        versionNumber: 1
      - IN: newReplicas
        applyTo:
          - none
          - nginx-manifest3
   #       - busybox-manifest2 

  - name: replace-deploy
    type: deploy
    method: replace
    maxWaitTime: 30
    steps:
   #   - IN: test-manifest
      - IN: nginx-manifest3
  #    - IN: busybox-manifest2 
      - IN: awsKeysCluster
  #   - IN: myLoadBalancer
  #      applyTo:
  #        - manifest: nginx-manifest3
  #          image: nginx-image
  #          port: 27017
  #    - IN: myOtherDockerOptions
  #- IN: zeroReplicas
 #       versionNumber: 1
      - IN: newReplicas
  #      applyTo:
  #        - none
  #        - manifest: nginx-manifest3
        
  - name: upgrade-deploy
    type: deploy
    method: upgrade
    steps:
   #   - IN: test-manifest
      - IN: nginx-manifest3
      - IN: awsKeysCluster
#      - IN: myLoadBalancer
#        applyTo:
#          - manifest: nginx-manifest3
#            image: nginx-image
#            port: 27017
      - IN: myOtherDockerOptions
      - IN: zeroReplicas
        versionNumber: 1
  #    - IN: otherPolicy
      - IN: newReplicas
        applyTo:
          - none
   #       - manifest: nginx-manifest3


  - name: runSh-shippable-yml
    type: runSh
    flags: shippable-yml
    runtime:
      architecture: x86_64		
      os: Ubuntu_14.04
    steps:
     - IN: test-repo2
 #      versionNumber: 5
     - TASK:
        - script: sleep 400
        - script: "echo true"
        
        
  - name: runSh-object
    type: runSh
    flags: shippable-yml
    runtime:
      architecture: x86_64		
      os: Ubuntu_14.04
    steps:
     - IN: test-repo2
 #      versionNumber: 5
     - TASK:
         script:
           - "echo true"
        
  - name: runSh-no-task
    type: runSh
    flags: shippable-yml
    runtime:
      architecture: x86_64		
      os: Ubuntu_14.04
    steps:
     - IN: test-repo2

  - name: CLI_config_test
    type: runCLI
    runtime:
      architecture: x86_64		
      os: CentOS_7
    steps:
      - IN: gke_Config_Resource
      - TASK:
        - script: echo "test"
 
  - name: azure_test
    type: runSh
    runtime:
      architecture: x86_64		
      os: CentOS_7
    steps:
      - IN: gke_Config_Resource
   #   - IN: myAzureCluster
   #   - IN: image-resource
      - IN: trigger-shippable-yml
      - IN: rename-repo5
      - TASK:
        - script: shipctl get_resource_version_key rename-repo5 version
        - script: echo "RENAMEREPO5_POINTER_TEST $RENAMEREPO5_POINTER_TEST"
        - script: echo "RENAMEREPO5_POINTER_TEST2 $RENAMEREPO5_POINTER_TEST2"
        - script: echo "RENAMEREPO5_POINTER_TEST3 $RENAMEREPO5_POINTER_TEST3"
