# Language setting
language: python

python:
  - 2.7

build:
  ci:
    - python --version

resources:

  - name: trigger-shippable-yml
    type: trigger
    flags: shippable-yml
    version:
      count: I

  - name: rename-repo5
    type: gitRepo
    integration: github
    pointer:
      sourceName: a-murphy/testRename5
      branch: master
      buildOnPullRequest: true
      buildOnPullRequestClose: true
      buildOnCommit: false
      test: $PWD
      test2: $RESOURCE_ID
      test3: $TRIGGERSHIPPABLEYML_VERSIONNUMBER
    version:
      version: $TRIGGERSHIPPABLEYML_VERSIONID

jobs:
  - name: runSh-shippable-yml
    type: runSh
    flags: shippable-yml
    steps:
     - TASK:
        - script: "echo true"
 
  - name: azure_test
    type: runSh  
    runtime:
      architecture: x86_64		
      os: Ubuntu_16.04
    steps:
   #   - IN: image-resource
   #   - IN: myLoadBalancer
   #     showBuildStatus: true
      - IN: trigger-shippable-yml
      - IN: rename-repo5
      - OUT: testRename5_ciRepo
    #  - IN: file2
    #    pull: true
      - TASK:
        - script: shipctl get_resource_version_key rename-repo5 version
        - script: echo "RENAMEREPO5_POINTER_TEST $RENAMEREPO5_POINTER_TEST"
        - script: echo "RENAMEREPO5_POINTER_TEST2 $RENAMEREPO5_POINTER_TEST2"
        - script: echo "RENAMEREPO5_POINTER_TEST3 $RENAMEREPO5_POINTER_TEST3"
        - script: echo "MYAZURECLUSTER_SOURCENAME $MYAZURECLUSTER_SOURCENAME"
        - script: echo "IMAGERESOURCE_SOURCENAME $IMAGERESOURCE_SOURCENAME"
        - script: echo "MYLOADBALANCER_SOURCENAME $MYLOADBALANCER_SOURCENAME"
