jobs:
 # - name: generate-mongo-image-manifest-3
#    type: manifest
 #   steps:
 #     - GET: mongo-image
  #    - GET: myEcsParams

  - name: foo
    type: release
    options:
      action: none
    steps:
      - GET: version-resource-3
      - GET: myEcsParams
      - GET: version-resource-5
      #- GET: generate-manifest
      - GET: triggerOne
      
  - name: foo3
    type: release
    options:
      action: none
    steps:
      GET: version-resource-3
      
            
  - type: release

  - name: generate-mongo-image-manifest-6
    type: manifest
    steps:
      - GET: mongo-image
      - GET: triggerOne
  #    - GET: generate-manifest
  #    - GET: myEcsParams
  #      applyTo:
  #        - image
      
      - GET: myOtherEcsParams
#      - GET: deploy-service
      - GET: myOtherDockerOptions
        applyTo:
          - mongo-image

  - name: generate-manifest
    type: manifest
    steps:
      - GET: mongo-image
      - GET: myReplicas
#      - GET: deploy-service
    #  - GET: myOtherDockerOptions

 # - name: deploy-service
#    type: ecsDeploy
#    steps:
#      - GET: generate-mongo-image-manifest-3
#      - GET: myEcsCluster

  - name: deploy-service-7
    type: dclDeploy
    steps:
      - GET: generate-manifest
      - GET: myDclCluster
      - GET: myEcsParams
        applyTo:
          - other
      - GET: myOtherEcsParams

  - name: deploy-7
    type: dclDeploy
    steps:
      - GET: generate-mongo-image-manifest-6
      - GET: myDclCluster
      - GET: myEcsParams
      - GET: myOtherEcsParams
 
  - name: deploy-service-8
    type: ecsDeploy
    steps:
      - GET: generate-mongo-image-manifest-6
      - GET: myEcsCluster
     # - GET: myReplicas
#      - GET: deploy-service-7
      - GET: myEcsParams
        applyTo:
          - other-image
      - GET: myOtherEcsParams
        applyTo:
          - mongo-image
 
  - name: deploy-service-10
    type: ecsDeploy
    steps:
      - GET: generate-mongo-image-manifest-6
   #   - GET: myEcsCluster
      - GET: myOtherDockerOptions
   #   - GET: myReplicas
   #   - GET: deploy-service-7
      - GET: myEcsParams
   #   - GET: myOtherEcsParams

  - name: CI-project
    type: runCI
    steps:
      - GET: myEcsParams
      - PUT: mongo-image
      - GET: projectToTrigger
