# Language setting
language: python

python:
  - 2.7

build:
  ci:
    - python --version

resources:
  - name: testParamsValue
    type: params
    versionTemplate:
      params:
   #     secure: AYgkVcr+hwoqDnHDCzHrkePBCTyDx249LqX+3XO6w4pVi54QBDO9PneuDBA2Py9fbjB7q2JwzJZy3zsfY1eNO5DjSaAnXBl3CJVrMySJPXhaXHaWAhVXZ3G7agz0Y3hyByAeIJx3ozvZlq1Ky3WH5k08rkrUP9zMYxxH8tNOCT/wUnFwFSn64axuWfzoDWpfhzfM86UhspW8/4FgYuAirSmLyYYvUfELh9zUNrNkP0aBGLMgTMb97unqVqaLEWoOzu4p1q/EMa4kJ3541Wqa24EtSN/b+FRRuOZWFb4JlK5WyHtvuc1juOheVoEzXdLMWsdJeGO8HfO/8GBx0o8fNg== 
   #     secure: hM5vTNW21fHHdr1cgZkUywyL1azcSGHXDLQ8YPz571WrnGLR/jD+RojMfccvZVukMyGJ22r6xJqh0VKanhH0O/Tx4V3CdqLuszPulZzGSV2dSToD/fqu8vRiREKEa78dOW8ZFXKrL8x0+PcxdbUYaHFEpg8a11hLJSozsxoXwsNxVFzz95yiNT0szMNkBlY06xTNtGPl8SdVvrJwnDGV+sA/PNsGHVrQlBxpz7xQvz4Mk72rtXIDIGYz26WdCs4Fh2VW64msEOC7d8RhhSDRXYhJsTDfAW7tjkhz3KOpX5ffE7QFzisaThXKXNOpdjtGTXjjqb/aa0AgQ6ATtKT0RQ==
        secure: e9h6nzFJXx/bN5GABL05bDeX0d/v5VOEYRJfb2bvkNSBScf9GxUq4C+Jz/wnrolNEl/5Sfa4eP7YaIqENrWgau7gkDKkut6JlAxVdMRRq9quJ+mqYyt8ldtKsDuxALCOkDuFr3utf+xQBhjMe1Fp45d8PCNVnpaIZV0goV0XAA1UWq4NEiMA5iwrnjzyshuZTTFZU/z0QbXv2F/Xiuz1aNcEBCcCT1lTyeCHpG9gxWFtFfHLDANLiyFeSXmLHoW+DjQfmBnRyVhGxpObSGErz2EZI6/GsekBSXTVIo27LaNJsfYjdMK1APERsE5qyrxUohIk8oblDhDxg50B8iKACw==
   #     secure: iKEupHAV89GzM0Kdq6+31MA4zREDK8EsX3Ka4cwfHsd4lUVdvDZdYjJFGOOeTCQOM3f9u4h+/xJC1/019f2Tt+uAv1vK290/LXVbMIDEIAk0lGKZuiz/bGSh8nwmK61iYdiUepZKGISMLN3P4Xy8i6izTrqq0ZHsU6Ef2DViI0OmBTwEO+JO4QBJVyLjeXsubYd2ee4hBadzCQFk+JlHQYwlFxUt6Si8wDmStRVOLWnPSG8SRL3Z8cUDSrV/u9ziIZyhK/ER2MAQpl1t2JFHtm9KJ+P62+zR/voCv3o+qjjlhaLxULaZlRMFGePDri/imbNtrAchf+G+PSH5hCBPZg==
    
  - name: paramsTest
    type: integration
    integration: testValue
      
  - name: test-image
    type: image
    pointer:
      sourceName: 544102397216.dkr.ecr.us-west-2.amazonaws.com/test/repository
    version:
      versionName: latest
      
  - name: 123_numbers
    type: image
    versionTemplate:
      sourceName: busybox
      versionName: latest
      
  - name: 123-testing-123
    type: image
    versionTemplate:
      versionName: $_NUMBERS_VERSIONNAME
      sourceName: $_FILEMANIFEST_NAME

  - name: 123-params
    type: params
    versionTemplate:
      params:
  #      123test: testing
        empty: ""

  - name: rename-repo5
    type: gitRepo
    integration: github
    pointer:
      sourceName: a-murphy/testRename5
      branch: master
      buildOnPullRequest: true
      buildOnPullRequestClose: true
      buildOnCommit: false
      test: $PWD
      test2: $RESOURCE_ID
      test3: $TRIGGERSHIPPABLEYML_VERSIONNUMBER
    version:
      version: $TRIGGERSHIPPABLEYML_VERSIONID

  - name: newReplicas
    type: replicas
    versionTemplate:
      count: 1
      minReplicas: 1
      maxReplicas: 2
  #    autoScalingRole: role
      autoScalingPolicies:
        - PolicyName: testPolicy
          PolicyType: "StepScaling"
          StepScalingPolicyConfiguration:
            AdjustmentType: "PercentChangeInCapacity"
            Cooldown: 60
            StepAdjustments:
              - MetricIntervalLowerBound: 0
                ScalingAdjustment: 150
         
        - PolicyName: testTargetPolicy
          PolicyType: "TargetTrackingScaling"
          TargetTrackingScalingPolicyConfiguration:
            TargetValue: 0.5
            PredefinedMetricSpecification:
              PredefinedMetricType: ECSServiceAverageCPUUtilization
            DisableScaleIn: false
            ScaleInCooldown: 0
            ScaleOutCooldown: 0

      metricAlarms:
        - AlarmName: "my-alarm"
          ComparisonOperator: "GreaterThanThreshold"
          EvaluationPeriods: 3
          MetricName: "CPUUtilization"
          Namespace: "AWS/ECS"
          Statistic: Average 
          Period: 60
          Threshold: 75.0
          Dimensions:
            - Name: ClusterName
              Value: test-cluster
            - Name: ServiceName
              Value: replace-deploy-nginx-manifest3
          AlarmActions:
            - testPolicy
                
  - name: otherPolicy
    type: replicas
    versionTemplate:
      count: 0
      autoScalingPolicies:
        - PolicyName: testPolicy2
          PolicyType: "StepScaling"
          StepScalingPolicyConfiguration:
            AdjustmentType: "PercentChangeInCapacity"
            Cooldown: 60
            StepAdjustments:
              - MetricIntervalLowerBound: 0
                ScalingAdjustment: 200
      

jobs:
  - name: bluegreen-deploy
    type: deploy
    method: blueGreen
    stabilityDuration: 30
    steps:
   #   - IN: test-manifest
      - IN: nginx-manifest3
   #   - IN: busybox-manifest2 
      - IN: myEcsCluster
      - IN: zeroReplicas
        versionNumber: 1
      - IN: newReplicas
        applyTo:
          - none
          - nginx-manifest3
   #       - busybox-manifest2 

  - name: replace-deploy
    type: deploy
    method: upgrade # replace
    maxWaitTime: 30
    steps:
     # - IN: test-manifest
      - IN: nginx-manifest3
  #    - IN: busybox-manifest2 
      - IN: myEcsCluster
      - IN: myLoadBalancer
        applyTo:
          - manifest: nginx-manifest3
            image: nginx-image
            port: 27017
  #    - IN: myOtherDockerOptions
  #- IN: zeroReplicas
 #       versionNumber: 1
      - IN: newReplicas
  #      applyTo:
  #        - none
  #        - manifest: nginx-manifest3
        
