jobs:
  - name: no-inputs
    type: runSh
    steps:
      - TASK:
        - script: "echo true"

  - name: provisionJob
    type: provision        
    steps:
      - IN: kubernetesLoadBalancer 
    on_success:
      - script: echo "Success"
      - NOTIFY: notifyMe
    on_failure:
      - script: echo "Failure"
      - NOTIFY: notifyMe

  - name: generate-manifest
    type: manifest
    steps:
      - IN: mongo-image
        switch: off
      - IN: nginx-image
      - IN: myDockerOptions
      - TASK: managed
